export const Emoticons = {
	PARTY_POPPER: '🎉',
	WRITING: '📝',
	PROF: '🤓',
	CALENDAR: '🗓️',
	LEFT_ARROW: '⬅️',
	RIGHT_ARROW: '➡️',
	CLOCK: '🕑',
	CHECK: '✅',
	EMPTY: '❓',
	NUMBERS: '🔢',
	LETTERS: '🔡',
	WARNING: '⚠️',
	NOTIFICATION: '🔔',
	MUTED: '🔕',
};
